### ISSUE TITLE
Generics bounds to strict in RepresentationModelAssemblerSupport

### ISSUE THREAD

**Issue by Bert-R** [spring-projects/spring-hateoas#1122]
With Spring Hateoas 0.25, we had code like this:

```
public class StatisticsResource extends Resource<StatisticsDto>
{
    :
}

public class StatisticsResourceAssembler
        extends ResourceAssemblerSupport<StatisticsDto, StatisticsResource>
{
    :
}
```

Now I'm migrating it to 1.0, like this:

```
public class StatisticsResource extends EntityModel<StatisticsDto>
{
    :
}

public class StatisticsResourceAssembler
        extends RepresentationModelAssemblerSupport<StatisticsDto, StatisticsResource>
{
    :
}
```

This however doesn't compile:
```
extends RepresentationModelAssemblerSupport<StatisticsDto, StatisticsResource>
                                                           ^
where D is a type-variable:
    D extends RepresentationModel<D> declared in class RepresentationModelAssemblerSupport
```

Any idea what's going wrong here?

P.S. I [asked this on StackOverflow](https://stackoverflow.com/questions/58755469/entity-model-inheritance-spring-hateoas-1-0) first and got the suggestion to use ``SimpleRepresentationModelAssembler``, but that only works for this simple case. We have more complex cases too.

**Comment by odrotbohm** [comment]
This is glitch in our generics declarations. Will be fixed ASAP.

**Comment by Bert-R** [comment]
Thanks a lot for the quick fix!

**Comment by Bert-R** [comment]
I have tested with the snapshot build and this is fixed. Thanks!

**Comment by margfernan** [comment]
Please, I'm having the same issue with spring boot 2.2.2 and spring Hateoas  v1. What is the version of Spring Hateoas with this issue solved?

**Comment by gregturn** [comment]
@margfernan If you use Spring Boot 2.3.0.BUILD-SNAPSHOT with `<spring-hateoas.version>` configured for `1.1.0.BUILD-SNAPSHOT`, you can take it out for a spin.

**Comment by margfernan** [comment]
@gregturn  thank you for your response but I tried with the version 1.1.0.BUILD-SNAPSHOT but the error still appears. When is released the new version of the spring hateoas with this fix? or, which version of spring hateoas is correct with Spring boot 2.2.2?

**Comment by odrotbohm** [comment]
As indicated by the error message you need to properly type `ClientResourceDto` to extends `RepresentationModel<ClientResourceDto>`.

The 1.1.0.BUILD-SNAPSHOTs should actually work with current Boot 2.2 as well. We could issue a first milestone of the former pretty soon if that helps. I'm afraid a GA release of Spring HATEOAS 1.1 is still a bit far out.

**Comment by Bert-R** [comment]
When I'm not mistaken, this is a compile-time fix that has no side-effects. Is it possible to backport this to 1.0.x and release it earlier?

**Comment by odrotbohm** [comment]
It changes API, which is why I was hesitant to back port it. On the other hand, IIUC it's completely unusable in the 1.0.x branch anyway, which means that there's nothing in there we can break even more than it already is broken, right?

**Comment by Bert-R** [comment]
Indeed, that's how I see it.

**Comment by odrotbohm** [comment]
Looks like we've already done this with #1126.

**Comment by Bert-R** [comment]
#1126 was included in 1.0.2.  I've tested this on 1.0.2 and can confirm it is fixed. 
@odrotbohm Thanks!

**Comment by margfernan** [comment]
> As indicated by the error message you need to properly type `ClientResourceDto` to extends `RepresentationModel<ClientResourceDto>`.
> 
> The 1.1.0.BUILD-SNAPSHOTs should actually work with current Boot 2.2 as well. We could issue a first milestone of the former pretty soon if that helps. I'm afraid a GA release of Spring HATEOAS 1.1 is still a bit far out.

It works! Thanks a lot!!
